[[services]]
name = "backend"
path = "backend"
dockerfilePath = "Dockerfile"
startCommand = "sh -c \"uvicorn app.main:app --host 0.0.0.0 --port $PORT\""

[[services]]
name = "sales"
path = "backend/Sales_for_AgentOS/agentos-sales"
dockerfilePath = "Dockerfile"
startCommand = "sh -c \"uvicorn app.main:app --host 0.0.0.0 --port $PORT\""

[variables]
MONGODB_URI = "your_mongodb_uri"
REDIS_URL = "your_redis_url"
AUTH_JWT_SECRET = "your_secret"
AUTH_ALGORITHM = "HS256"
GITHUB_PAT = "<seu_pat>"
GITHUB_REPO = "<owner/repo>"
GEMINI_API_KEY = "<sua_gemini_key>"
